name: plant_shop_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/plants/
  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/JosefinSans-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/JosefinSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/JosefinSans-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/JosefinSans-Light.ttf
          weight: 300
        - asset: assets/fonts/JosefinSans-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/JosefinSans-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JosefinSans-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSans-BoldItalic.ttf
          weight: 700
          style: italic
